version: '3.7'

services:
  db:
    container_name: mysql
    image: mysql

    environment:
      MYSQL_DATABASE: word
      MYSQL_USER: madmik
      MYSQL_PASSWORD: madmik
      MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - mysql_data:/var/lib/mysql # 네임드 볼륨
      - ./mysql/my.cnf:/etc/my.cnf
      - ./csv:/csv
      - ./mysql/import_data.sh:/docker-entrypoint-initdb.d/import_data.sh
    ports:
      - "3306:3306"
    restart: always 

  web:
    container_name: web 
    build:
      context: ./word
      dockerfile: Dockerfile
    

    volumes:
      - ./word:/word
      - logs:/var/log
  
  frontend:
    container_name: front
    build:
      context: ./word-front
      dockerfile: Dockerfile
    volumes:
      - front_build:/word-front/build
    # ports:
    #   - "3000:3000"

      
    restart: always


  nginx:
    container_name: nginx 
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl # SSL 인증서 볼륨 바인딩 추가
      - front_build:/word-front/build
    depends_on:
      - web
    restart: always



volumes: # 네임드 볼륨 선언
  mysql_data:
  logs:
  front_build: