version: '3.7'

services:
  db:
    container_name: mysql
    image: mysql

    environment:
      MYSQL_DATABASE: word
      MYSQL_USER: madmik
      MYSQL_PASSWORD: madmik
      MYSQL_ROOT_PASSWORD: 1234

    volumes:
      - mysql_data:/var/lib/mysql # 네임드 볼륨
    ports:
      - "3306:3306"
    restart: always 

  web:
    container_name: web 
    build:
      context: ./word
      dockerfile: Dockerfile
    network_mode: host

    volumes:
      - ./word:/word
      - logs:/var/log
  
  frontend:
    container_name: front
    build:
      context: ./word-front
      dockerfile: Dockerfile
    volumes:
      - front_build:/word-front/build
    # ports:
    #   - "3000:3000"

      
    restart: always

  


volumes: # 네임드 볼륨 선언
  mysql_data:
  logs:
  front_build: