# Generated by Django 4.2.4 on 2023-08-31 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('sound', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JpWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('kana', models.CharField(max_length=200)),
                ('sound', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KrWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('hangeul', models.CharField(max_length=200)),
                ('sound', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KrMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('meaning_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.krword', to_field='numbering')),
            ],
        ),
        migrations.CreateModel(
            name='KrExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500)),
                ('example_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.krmeaning', to_field='numbering')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.krword', to_field='numbering')),
            ],
        ),
        migrations.CreateModel(
            name='JpMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('meaning_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.jpword', to_field='numbering')),
            ],
        ),
        migrations.CreateModel(
            name='JpExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500)),
                ('example_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.jpmeaning', to_field='numbering')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.jpword', to_field='numbering')),
            ],
        ),
        migrations.CreateModel(
            name='CnMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=500)),
                ('meaning_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.cnword', to_field='numbering')),
            ],
        ),
        migrations.CreateModel(
            name='CnExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500)),
                ('example_numbering', models.CharField(max_length=200)),
                ('numbering', models.CharField(max_length=200, unique=True)),
                ('meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.cnmeaning', to_field='numbering')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.cnword', to_field='numbering')),
            ],
        ),
    ]
